In [125]:
from bs4 import BeautifulSoup as bsoup
from urllib.request import urlopen as uReq
import requests
import lxml
import pandas as pd
from pandas import DataFrame
import numpy as np

In [126]:
# list of postal codes in Canada where the first letter is M.- FROM Wikipedia (Web Scraping)
my_url='https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'

In [127]:
# Requests to get web page details from Wikipedia page 
r=requests.get(my_url)

In [128]:
# Parse the htlm with Soup
page=bsoup(r.text,"html.parser")
#page
rtable=page.table
rtable
results=rtable.find_all('tr')
nrows=len(results)
nrows
results=rtable.find_all('tr')
nrows=len(results)
print("###################################################################################")
print("Total Number of postal codes in Canada where the first letter is M is: ",nrows)
print("###################################################################################")

###################################################################################
Total Number of postal codes in Canada where the first letter is M is:  289
###################################################################################

In [129]:
header=results[0].text.split()
print("#####################################")
print("Headres from the extracted table")
print (header)
print("#####################################")

#####################################
Headres from the extracted table
['Postcode', 'Borough', 'Neighbourhood']
#####################################

In [130]:
#Iteration loop to extract all cells into a dataframe df_Loc_of_Neigh_Totonto as Postcode', 'Borough', 'Neighbourhood'

records =[]
n=1
while n < nrows :
    Postcode=results[n].text.split('\n')[1]
    Borough=results[n].text.split('\n')[2]
    Neighborhood=results[n].text.split('\n')[3]
    records.append((Postcode, Borough,Neighborhood))
    n=n+1
print("##########################################################################################")
print("Extreatced Data from the URL inserting into DataFrame in standard table format is python ")
print("##########################################################################################")
df_Loc_of_Neigh_Totonto=pd.DataFrame(records, columns=['PostalCode', 'Borough', 'Neighbourhood'])
df_Loc_of_Neigh_Totonto.head(5)

##########################################################################################
Extreatced Data from the URL inserting into DataFrame in standard table format is python
##########################################################################################

  PostalCode           Borough     Neighbourhood
0        M1A      Not assigned      Not assigned
1        M2A      Not assigned      Not assigned
2        M3A        North York         Parkwoods
3        M4A        North York  Victoria Village
4        M5A  Downtown Toronto      Harbourfront

In [131]:
df_Loc_of_Neigh_Totonto.tail()

    PostalCode       Borough          Neighbourhood
283        M8Z     Etobicoke              Mimico NW
284        M8Z     Etobicoke     The Queensway West
285        M8Z     Etobicoke  Royal York South West
286        M8Z     Etobicoke         South of Bloor
287        M9Z  Not assigned           Not assigned

In [132]:
print("Quick check of the shape")
df_Loc_of_Neigh_Totonto.shape

Quick check of the shape

(288, 3)

In [133]:
#How many Postal codes are not assigned to any Borough 
print("#######################################################")
print("How many Postal codes are not assigned to any Borough ")
print("#######################################################")
print(df_Loc_of_Neigh_Totonto[df_Loc_of_Neigh_Totonto['Borough']=='Not assigned'].count())

#######################################################
How many Postal codes are not assigned to any Borough
#######################################################
PostalCode       77
Borough          77
Neighbourhood    77
dtype: int64

In [134]:
# Drop the rows which is not assighed to and Borough' - data cleansing 
df_Loc_of_Neigh_Totonto1=df_Loc_of_Neigh_Totonto[~df_Loc_of_Neigh_Totonto.Borough.str.contains("Not assigned")]
df_Loc_of_Neigh_Totonto1=df1.reset_index(drop=True)
print("###########################################################################")
print("Data claensing has been done successfuly, by removing NOT ASSIGNED CATEGORY")
print("###########################################################################")

###########################################################################
Data claensing has been done successfuly, by removing NOT ASSIGNED CATEGORY
###########################################################################

In [135]:
df_Loc_of_Neigh_Totonto1.head(5)

  PostalCode           Borough     Neighbourhood
0        M3A        North York         Parkwoods
1        M4A        North York  Victoria Village
2        M5A  Downtown Toronto      Harbourfront
3        M5A  Downtown Toronto       Regent Park
4        M6A        North York  Lawrence Heights

In [136]:
df_Loc_of_Neigh_Totonto1.tail()

    PostalCode    Borough             Neighbourhood
206        M8Z  Etobicoke  Kingsway Park South West
207        M8Z  Etobicoke                 Mimico NW
208        M8Z  Etobicoke        The Queensway West
209        M8Z  Etobicoke     Royal York South West
210        M8Z  Etobicoke            South of Bloor

In [137]:
print("Quick check of the shape")
df_Loc_of_Neigh_Totonto1.shape

Quick check of the shape

(211, 3)

In [138]:
# We have to replace 'Not assigned' neighborhoods with the name of the Borough itself
df_Loc_of_Neigh_Totonto1.loc[df_Loc_of_Neigh_Totonto1['Neighbourhood'] == 'Not assigned', 'Neighbourhood'] = df_Loc_of_Neigh_Totonto1['Borough']

In [139]:
df_Loc_of_Neigh_Totonto1.head()

  PostalCode           Borough     Neighbourhood
0        M3A        North York         Parkwoods
1        M4A        North York  Victoria Village
2        M5A  Downtown Toronto      Harbourfront
3        M5A  Downtown Toronto       Regent Park
4        M6A        North York  Lawrence Heights

In [140]:
print("Quick check of the shape")
df_Loc_of_Neigh_Totonto1.shape

Quick check of the shape

(211, 3)

In [141]:
# Postalcode consolidation process

print("######################################")
print("Postalcode consolidation process")
print("######################################")

postalcodes = df_Loc_of_Neigh_Totonto1['PostalCode'].nunique()
boroughs = df_Loc_of_Neigh_Totonto1['Borough'].nunique()
neighbourhoods= df_Loc_of_Neigh_Totonto1['Neighbourhood'].nunique()
print('Unique Postalcodes : ' + str(postalcodes))
print('Unique Boroughs  : '+ str(boroughs))
print('Unique Neighbourhoods  :' + str(neighbourhoods))

######################################
Postalcode consolidation process
######################################
Unique Postalcodes : 103
Unique Boroughs  : 11
Unique Neighbourhoods  :209

In [142]:
print("############################################")
print("Postalcode consolidation process, Group By")
print("############################################")

df_Loc_of_Neigh_Totonto1.groupby(['PostalCode','Borough','Neighbourhood']).size().reset_index(name='Count').head()

############################################
Postalcode consolidation process, Group By
############################################

  PostalCode      Borough   Neighbourhood  Count
0        M1B  Scarborough         Malvern      1
1        M1B  Scarborough           Rouge      1
2        M1C  Scarborough  Highland Creek      1
3        M1C  Scarborough      Port Union      1
4        M1C  Scarborough      Rouge Hill      1

In [143]:
nrows1=len(df_Loc_of_Neigh_Totonto1)
nrows1

211

In [144]:
df_Loc_of_Neigh_Totonto12=df_Loc_of_Neigh_Totonto1
df_Loc_of_Neigh_Totonto12.head()

  PostalCode           Borough     Neighbourhood
0        M3A        North York         Parkwoods
1        M4A        North York  Victoria Village
2        M5A  Downtown Toronto      Harbourfront
3        M5A  Downtown Toronto       Regent Park
4        M6A        North York  Lawrence Heights

In [145]:
nrows2=len(df_Loc_of_Neigh_Totonto1)-1
nrows2

210

In [146]:
#To extract the consolidate dataframe df_Loc_of_Neigh_Totonto12 with unique postalcodes.

n=0

while n < nrows2 :
    post1=df_Loc_of_Neigh_Totonto12.iloc[n,0]
    #post1
    m=n+1
    post2=df_Loc_of_Neigh_Totonto12.iloc[m,0]
    #post2
    neigh1=df_Loc_of_Neigh_Totonto12.iloc[n,2]
    neigh2=df_Loc_of_Neigh_Totonto12.iloc[m,2]
    if post1==post2:
        df_Loc_of_Neigh_Totonto12.Neighbourhood[n,2] = neigh1=neigh1+','+neigh2
        #df2 = df2[df2.Neighbourhood != 'neigh2']
        df_Loc_of_Neigh_Totonto12=df_Loc_of_Neigh_Totonto12.drop(df_Loc_of_Neigh_Totonto12.index[m])
        nrows2=nrows2-1
        df_Loc_of_Neigh_Totonto12 = df_Loc_of_Neigh_Totonto12.reset_index(drop=True)
    else:
        n=n+1

df_Loc_of_Neigh_Totonto12.index

RangeIndex(start=0, stop=103, step=1)

In [147]:
df_Loc_of_Neigh_Totonto12.head()

,PostalCode,Borough,Neighbourhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,"Kingsway Park South West,Mimico NW,The Queensw..."
3,M6A,North York,"Lawrence Heights,Lawrence Manor"
4,M7A,Queen's Park,Queen's Park

In [148]:
df_Loc_of_Neigh_Totonto12.index

RangeIndex(start=0, stop=103, step=1)

In [149]:
df_Loc_of_Neigh_Totonto12

,PostalCode,Borough,Neighbourhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,"Kingsway Park South West,Mimico NW,The Queensw..."
3,M6A,North York,"Lawrence Heights,Lawrence Manor"
4,M7A,Queen's Park,Queen's Park
5,M9A,Etobicoke,Islington Avenue
6,M1B,Scarborough,"Rouge,Malvern"
7,M3B,North York,Don Mills North
8,M4B,East York,"Woodbine Gardens,Parkview Hill"
9,M5B,Downtown Toronto,"Ryerson,Garden District"
10,M6B,North York,Glencairn
11,M9B,Etobicoke,"Cloverdale,Islington,Martin Grove,Princess Gar..."
12,M1C,Scarborough,"Highland Creek,Rouge Hill,Port Union"
13,M3C,North York,"Flemingdon Park,Don Mills South"
14,M4C,East York,Woodbine Heights
15,M5C,Downtown Toronto,St. James Town
16,M6C,York,Humewood-Cedarvale
17,M9C,Etobicoke,"Bloordale Gardens,Eringate,Markland Wood,Old B..."
18,M1E,Scarborough,"Guildwood,Morningside,West Hill"
19,M4E,East Toronto,The Beaches
20,M5E,Downtown Toronto,Berczy Park
21,M6E,York,Caledonia-Fairbanks
22,M1G,Scarborough,Woburn
23,M4G,East York,Leaside
24,M5G,Downtown Toronto,Central Bay Street
25,M6G,Downtown Toronto,Christie
26,M1H,Scarborough,Cedarbrae
27,M2H,North York,Hillcrest Village
28,M3H,North York,"Bathurst Manor,Downsview North,Wilson Heights"
29,M4H,East York,Thorncliffe Park
...,...,...,...
73,M4R,Central Toronto,North Toronto West
74,M5R,Central Toronto,"The Annex,North Midtown,Yorkville"
75,M6R,West Toronto,"Parkdale,Roncesvalles"
76,M7R,Mississauga,Canada Post Gateway Processing Centre
77,M9R,Etobicoke,"Kingsview Village,Martin Grove Gardens,Richvie..."
78,M1S,Scarborough,Agincourt
79,M4S,Central Toronto,Davisville
80,M5S,Downtown Toronto,"Harbord,University of Toronto"
81,M6S,West Toronto,"Runnymede,Swansea"
82,M1T,Scarborough,"Clarks Corners,Sullivan,Tam O'Shanter"
83,M4T,Central Toronto,"Moore Park,Summerhill East"
84,M5T,Downtown Toronto,"Chinatown,Grange Park,Kensington Market"
85,M1V,Scarborough,"Agincourt North,L'Amoreaux East,Milliken,Steel..."
86,M4V,Central Toronto,"Deer Park,Forest Hill SE,Rathnelly,South Hill,..."
87,M5V,Downtown Toronto,"CN Tower,Bathurst Quay,Island airport,Harbourf..."
88,M8V,Etobicoke,"Humber Bay Shores,Mimico South,New Toronto"
89,M9V,Etobicoke,"Albion Gardens,Beaumond Heights,Humbergate,Jam..."
90,M1W,Scarborough,L'Amoreaux West
91,M4W,Downtown Toronto,Rosedale
92,M5W,Downtown Toronto,Stn A PO Boxes 25 The Esplanade
93,M8W,Etobicoke,"Alderwood,Long Branch"
94,M9W,Etobicoke,Northwest
95,M1X,Scarborough,Upper Rouge
96,M4X,Downtown Toronto,"Cabbagetown,St. James Town"
97,M5X,Downtown Toronto,"First Canadian Place,Underground city"
98,M8X,Etobicoke,"The Kingsway,Montgomery Road,Old Mill North"
99,M4Y,Downtown Toronto,Church and Wellesley
100,M7Y,East Toronto,Business Reply Mail Processing Centre 969 Eastern
101,M8Y,Etobicoke,"Humber Bay,King's Mill Park,Kingsway Park Sout..."
102,M8Z,Etobicoke,"Kingsway Park South West,Mimico NW,The Queensw..."

In [150]:
print("Quick check of the shape")
df_Loc_of_Neigh_Totonto12.shape

Quick check of the shape

(103, 3)

In [151]:
import json # library to handle JSON files

#!conda install -c conda-forge geopy --yes # uncomment this line if you haven't completed the Foursquare API lab
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

#import geocoder

ModuleNotFoundError: No module named 'geopy'

In [152]:
#Getting Latitude and Longitude date 
url='http://cocl.us/Geospatial_data'
df_pll=pd.read_csv(url)
df_pll.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [153]:
df_pll.columns = ['PostalCode', 'Latitude', 'Longitude']
df_pll.head()

  PostalCode   Latitude  Longitude
0        M1B  43.806686 -79.194353
1        M1C  43.784535 -79.160497
2        M1E  43.763573 -79.188711
3        M1G  43.770992 -79.216917
4        M1H  43.773136 -79.239476

In [154]:
df_Loc_of_Neigh_Totonto12s=df_Loc_of_Neigh_Totonto12.sort_values('PostalCode')
df_Loc_of_Neigh_Totonto12s.head()

   PostalCode      Borough                         Neighbourhood
6         M1B  Scarborough                         Rouge,Malvern
12        M1C  Scarborough  Highland Creek,Rouge Hill,Port Union
18        M1E  Scarborough       Guildwood,Morningside,West Hill
22        M1G  Scarborough                                Woburn
26        M1H  Scarborough                             Cedarbrae

In [155]:
#Merging to dataframe - Postal code Borough and Latitude/Longitude. to achive the objective

df_neighborhoods=pd.merge(df_Loc_of_Neigh_Totonto12s,df_pll, how='right', on = 'PostalCode')
df_neighborhoods.head(15)

,PostalCode,Borough,Neighbourhood,Latitude,Longitude
0,M1B,Scarborough,"Rouge,Malvern",43.806686,-79.194353
1,M1C,Scarborough,"Highland Creek,Rouge Hill,Port Union",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood,Morningside,West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
5,M1J,Scarborough,Scarborough Village,43.744734,-79.239476
6,M1K,Scarborough,"East Birchmount Park,Ionview,Kennedy Park",43.727929,-79.262029
7,M1L,Scarborough,"Clairlea,Golden Mile,Oakridge",43.711112,-79.284577
8,M1M,Scarborough,"Cliffcrest,Cliffside,Scarborough Village West",43.716316,-79.239476
9,M1N,Scarborough,"Birch Cliff,Cliffside West",43.692657,-79.264848
10,M1P,Scarborough,"Dorset Park,Scarborough Town Centre,Wexford He...",43.757410,-79.273304
11,M1R,Scarborough,"Maryvale,Wexford",43.750072,-79.295849
12,M1S,Scarborough,Agincourt,43.794200,-79.262029
13,M1T,Scarborough,"Clarks Corners,Sullivan,Tam O'Shanter",43.781638,-79.304302
14,M1V,Scarborough,"Agincourt North,L'Amoreaux East,Milliken,Steel...",43.815252,-79.284577